# I18nLite 本地开发配置文件
server:
  port: 8000
  mode: debug

database:
  host: localhost  # 本地开发直接连接localhost
  port: 3306
  username: i18n_user
  password: i18n_password  
  database: i18n_lite
  charset: utf8mb4
  parseTime: true
  loc: Local

upload:
  max_size: 10 # MB
  allowed_types: [".po", ".xlsx", ".xls"]
  temp_dir: "./temp"

log:
  level: debug # 本地开发使用debug级别
  file: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
