# I18nLite 配置文件
server:
  port: 8000
  mode: debug # debug, release

database:
  host: mysql  # Docker环境使用服务名，本地开发可改为localhost
  port: 3306
  username: i18n_user  # 与docker-compose保持一致
  password: i18n_password
  database: i18n_lite
  charset: utf8mb4
  parseTime: true
  loc: Local

upload:
  max_size: 10 # MB
  allowed_types: [".po", ".xlsx", ".xls"]
  temp_dir: "./temp"

log:
  level: debug # debug, info, warn, error
  file: "./logs/app.log"
  max_size: 100 # MB
  max_backups: 3
  max_age: 28 # days
